# Generated by Django 4.2 on 2025-07-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_alter_blogimages_image_alter_sword_img_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='phone',
            field=models.CharField(default='515-555-5555', max_length=100),
        ),
    ]
