# Generated by Django 4.2 on 2025-07-27 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_ordersettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
    ]
