# Generated by Django 4.2 on 2025-07-29 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_alter_blog_options'),
        ('projects', '0033_alter_blog_options_alter_pagecontent_page_section'),
    ]

    operations = [
    ]
