# Generated by Django 4.2 on 2025-07-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_merge_20250729_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='page_section',
            field=models.CharField(choices=[('sales_page_payment_info', 'Sales Page - Payment Information'), ('about_biography', 'About Page - Howard Clark Biography'), ('sword_order_payment_instructions', 'Order Form - Payment Instructions'), ('sword_order_info_section', 'Order Form - Rules & Pricing'), ('classes_general_info', 'Classes Page - General Information'), ('classes_payment_instructions', 'Classes Page - Payment Instructions'), ('classes_address_info', 'Classes Page - Address Information'), ('classes_materials_info', 'Classes Page - Materials Information'), ('classes_equipment_requirements', 'Classes Page - Equipment Requirements'), ('classes_safety_equipment', 'Classes Page - Safety Equipment'), ('classes_practice_recommendations', 'Classes Page - Practice Recommendations'), ('classes_one_on_one_info', 'Classes Page - One-on-One Lessons'), ('orders_disabled_title', 'Orders Disabled - Title'), ('orders_disabled_message', 'Orders Disabled - Message'), ('blog_page_greeting', 'Blog Page - Greeting Text')], help_text='Select which section of the website this content belongs to', max_length=50, unique=True),
        ),
    ]