# Generated by Django 4.2 on 2026-01-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_alter_pagecontent_page_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='page_section',
            field=models.CharField(choices=[('sales_page_payment_info', 'Sales Page - Payment Information'), ('about_biography', 'About Page - Howard Clark Biography'), ('sword_order_word_block', 'Order Form - word block'), ('classes_word_block', 'Classes Page - Word Block'), ('orders_disabled_title', 'Orders Disabled - Title'), ('orders_disabled_message', 'Orders Disabled - Message'), ('blog_page_greeting', 'Blog Page - Greeting Text')], help_text='Select which section of the website this content belongs to', max_length=50, unique=True),
        ),
    ]
